name: Test a GitCode pull request

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number in cann/catlass on GitCode
        required: true
        type: string

permissions:
  contents: read

jobs:
  merge-and-test:
    uses: ascend-catlass/actions/.github/workflows/test-gitcode-pr.yml@main
    with:
      pr_number: ${{ inputs.pr_number }}
    secrets:
      GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
